-- https://www.hackerrank.com/challenges/the-pads/problem?isFullScreen=true
SELECT 
CONCAT(NAME, '','(',SUBSTR(OCCUPATION, 1, 1),')') 
FROM OCCUPATIONS
ORDER BY NAME;

SELECT CONCAT('There are a total of ', TOTAL, ' ', OCCUPATION, '.')
FROM (
    SELECT CONCAT(LOWER(OCCUPATION), 's') as OCCUPATION, COUNT(OCCUPATION) as TOTAL
    FROM OCCUPATIONS
    GROUP BY OCCUPATION
    ORDER BY TOTAL
) AS GROUPED_OCCUPATIONS;